### PR TITLE
Fix #640

### LINKED ISSUE #640: Exception thrown when invoking [_channel unsubscribe]
We sometimes experience an exception being thrown for [_channel unsubscribe];

The full stacktrace can be found below. This happens intermittently for us and we can't reliably reproduce the issue.

for now we just added try catch around [unsubscribe] hopefully it doesn't crash our users anymore.

```
Fatal Exception: NSGenericException
*** Collection <__NSArrayM: 0x173c0540> was mutated while being enumerated.
-[ARTEventEmitter resetListeners]
 Raw Text

Fatal Exception: NSGenericException
0  CoreFoundation                 0x1b4bfb3d __exceptionPreprocess
1  libobjc.A.dylib                0x1a747067 objc_exception_throw
2  CoreFoundation                 0x1b4bf5e1 -[NSException name]
3  MY TEST CI                 0x1f7805 -[ARTEventEmitter resetListeners] (ARTEventEmitter.m:258)
4  MY TEST CI                 0x20cb15 -[ARTRealtimeChannel unsubscribe] (ARTRealtimeChannel.m:301)
5  MY TEST CI                 0x16d815 -[AblyManager unsubscribeFromChannelNamed:] (AblyManager.m:25)
6  MY TEST CI                 0x153001 -[BroadcastDisplayerViewController dismissController] (BroadcastDisplayerViewController.m:353)
7  UIKit                          0x207263b5 -[UIApplication sendAction:to:from:forEvent:]
8  UIKit                          0x20726349 -[UIControl sendAction:to:forEvent:]
9  UIKit                          0x20710979 -[UIControl _sendActionsForEvents:withEvent:]
10 UIKit                          0x20725c85 -[UIControl touchesEnded:withEvent:]

```

### PR DESCRIPTION
**Pull request by ricardopereira**
#640

### CODE REVIEW

**Comment by ricardopereira** [comment]
d6353e1 test raises a EXC_BAD_INSTRUCTION in `[ARTRealtimeChannel unsubscribe]` because of a `_dispatch_barrier_sync_f_slow `:

screen shot 2017-11-09 at 19 27 31

**Comment by tcard** [comment]
@ricardopereira This is expected. You can't call `unsubscribe` from an `internalEventEmitter`, since a `internalEventEmitter` works exclusively within the internal queue, already holding the lock.

I'll comment on the issue what I think the problem is.

**Comment by ricardopereira** [comment]
(3e1bd48) Another try to reproduce the issue but no success.

**Comment by ricardopereira** [comment]
@tcard I think we just need to change the `ARTInternalEventEmitter` to `ARTPublicEventEmitter`. 

https://github.com/ably/ably-ios/blob/2027ee3690f5fa2af3c1f629d8471934d6e79348/Source/ARTRealtimeChannel.m#L418-L420

https://github.com/ably/ably-ios/blob/2027ee3690f5fa2af3c1f629d8471934d6e79348/Source/ARTRealtimeChannel.m#L66

**Comment by tcard** [comment]
@ricardopereira No, that's for dispatching to the internal queue when the user is in the user (main) queue. This is the other way around, from the internal queue we need to dispatch to the user queue. And this needs to happen for internal event emitters too, at least those that potentially hold references to user objects.

**Comment by ricardopereira** [comment]
> This is the other way around, from the internal queue we need to dispatch to the user queue.

@tcard But we are already doing that by encapsulating each user callback with our implementation which dispatches the callback to the user queue:

```
    if (cb) {
        void (^userCallback)(ARTMessage *__art_nullable m) = cb;
        cb = ^(ARTMessage *__art_nullable m) {
            ART_EXITING_ABLY_CODE(_realtime.rest);
            dispatch_async(_userQueue, ^{
                userCallback(m);
            });
        };
    }
```

**Comment by tcard** [comment]
@ricardopereira Right, and that's perfect, but what I didn't anticipate is that there's another way of executing user code from our internal queue: by causing some of their object's reference counts to drop to zero, hence automatically calling their `dealloc` method. Which is exactly what happened at #640.

When `off` is called, we drop the reference to a callback, and that callback may be holding references to other objects, and those objects may have a `dealloc` method. Hence, dropping references to user callbacks must be executed in the user queue, not in our internal queue.

File: Spec/RealtimeClient.swift [hunk 1]
```diff
@@ -1355,7 +1355,7 @@ class RealtimeClient: QuickSpec {
             }
 
             // Possible issue of https://github.com/ably/ably-ios/issues/640
-            fit("should dispatch in user queue") {
+            xit("should dispatch in user queue") {
```
Comment (tcard) [inline Spec/RealtimeClient.swift]: This should be fixed.

File: Spec/RealtimeClient.swift [hunk 2]
```diff
@@ -1328,6 +1328,56 @@ class RealtimeClient: QuickSpec {
                 expect(result).to(equal(expectedOrder))
             }
 
+            // Possible issue of https://github.com/ably/ably-ios/issues/640
+            xit("should unlock queue when the timer ends") {
```
Comment (tcard) [inline Spec/RealtimeClient.swift]: I think we can remove this one, the other reproduces the issue more clearly from a user persoective without meddling with the internal emitter.

File: Spec/RealtimeClient.swift [hunk 3]
```diff
@@ -1328,6 +1328,56 @@ class RealtimeClient: QuickSpec {
...
+                    }
+                    func update() {
+                    }
+                    func close() {
+                        AblyManager.sharedClient.channels.get(channel).unsubscribe()
+                    }
+                }
+
+                let foo = Foo()
+                foo.close()
```
Comment (tcard) [inline Spec/RealtimeClient.swift]: Hmm, does this really reproduce the issue? I think if you call `close` here, then it will remove the listener you add at `init` but since you still have a reference to the created object its `deinit` won't be called, and when you drop the reference just after, since you already removed the listener, its `deinit`'s `unsubscribe` will just do nothing.

I think `deinit` should just call `unsubscribe` directly; we don't need `close`.

Please confirm this reproduces the issue by commenting out the `dispatch_async` in `removeListener` and making sure this test then fails, and stops failing if you put it back.

Comment (ricardopereira) [reply Spec/RealtimeClient.swift]: > Hmm, does this really reproduce the issue?

I think so but it always pass. I'll change the code with your points.

Comment (ricardopereira) [reply Spec/RealtimeClient.swift]: It always passes d0b8aeb

Comment (ricardopereira) [reply Spec/RealtimeClient.swift]: Should we ask the client to test using the branch?

Comment (tcard) [reply Spec/RealtimeClient.swift]: @ricardopereira Yes, but we also need to have a test that actually reproduces the problem. Maybe instead of `self` we can reference a different object, then make sure we drop the other reference to it before dropping the reference to `foo`?

**Comment by ricardopereira** [comment]
Success!

screen shot 2017-11-16 at 17 10 13

**Comment by ricardopereira** [comment]
Squashed.
